services:
  kafka:
    hostname: kafka
    image: 'bitnami/kafka:3.3.2'
    restart: always
    ports:
      - '9093:9093'
    networks:
      - go-kit
    environment:
    - "KAFKA_CFG_NODE_ID=0"
    - "KAFKA_CFG_PROCESS_ROLES=controller,broker"
    - "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9094"
    - "KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER"
    - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
    - "KAFKA_CFG_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093,CONTROLLER://:9094"
    - "KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://localhost:9093"
    - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - "KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE"
networks:
  go-kit: {}